// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace msg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class Body;
class Header;
class Msg;

// ===================================================================

class Header : public ::google::protobuf::Message {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  inline Header* New() const { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::uint32 version() const;
  void set_version(::google::protobuf::uint32 value);

  // required uint32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // required uint32 sm_id = 3;
  bool has_sm_id() const;
  void clear_sm_id();
  static const int kSmIdFieldNumber = 3;
  ::google::protobuf::uint32 sm_id() const;
  void set_sm_id(::google::protobuf::uint32 value);

  // optional uint32 action_id = 4;
  bool has_action_id() const;
  void clear_action_id();
  static const int kActionIdFieldNumber = 4;
  ::google::protobuf::uint32 action_id() const;
  void set_action_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:msg.Header)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_sm_id();
  inline void clear_has_sm_id();
  inline void set_has_action_id();
  inline void clear_has_action_id();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 version_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 sm_id_;
  ::google::protobuf::uint32 action_id_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// -------------------------------------------------------------------

class Body : public ::google::protobuf::Message {
 public:
  Body();
  virtual ~Body();

  Body(const Body& from);

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Body& default_instance();

  void Swap(Body* other);

  // implements Message ----------------------------------------------

  inline Body* New() const { return New(NULL); }

  Body* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(Body)
  // @@protoc_insertion_point(class_scope:msg.Body)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Body* default_instance_;
};
// -------------------------------------------------------------------

class Msg : public ::google::protobuf::Message {
 public:
  Msg();
  virtual ~Msg();

  Msg(const Msg& from);

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg& default_instance();

  void Swap(Msg* other);

  // implements Message ----------------------------------------------

  inline Msg* New() const { return New(NULL); }

  Msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg& from);
  void MergeFrom(const Msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .msg.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::msg::Header& header() const;
  ::msg::Header* mutable_header();
  ::msg::Header* release_header();
  void set_allocated_header(::msg::Header* header);

  // optional .msg.Body body = 2;
  bool has_body() const;
  void clear_body();
  static const int kBodyFieldNumber = 2;
  const ::msg::Body& body() const;
  ::msg::Body* mutable_body();
  ::msg::Body* release_body();
  void set_allocated_body(::msg::Body* body);

  // @@protoc_insertion_point(class_scope:msg.Msg)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_body();
  inline void clear_has_body();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::msg::Header* header_;
  ::msg::Body* body_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Msg* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Header

// required uint32 version = 1;
inline bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Header::version() const {
  // @@protoc_insertion_point(field_get:msg.Header.version)
  return version_;
}
inline void Header::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:msg.Header.version)
}

// required uint32 type = 2;
inline bool Header::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 Header::type() const {
  // @@protoc_insertion_point(field_get:msg.Header.type)
  return type_;
}
inline void Header::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:msg.Header.type)
}

// required uint32 sm_id = 3;
inline bool Header::has_sm_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_sm_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_sm_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_sm_id() {
  sm_id_ = 0u;
  clear_has_sm_id();
}
inline ::google::protobuf::uint32 Header::sm_id() const {
  // @@protoc_insertion_point(field_get:msg.Header.sm_id)
  return sm_id_;
}
inline void Header::set_sm_id(::google::protobuf::uint32 value) {
  set_has_sm_id();
  sm_id_ = value;
  // @@protoc_insertion_point(field_set:msg.Header.sm_id)
}

// optional uint32 action_id = 4;
inline bool Header::has_action_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_action_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_action_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_action_id() {
  action_id_ = 0u;
  clear_has_action_id();
}
inline ::google::protobuf::uint32 Header::action_id() const {
  // @@protoc_insertion_point(field_get:msg.Header.action_id)
  return action_id_;
}
inline void Header::set_action_id(::google::protobuf::uint32 value) {
  set_has_action_id();
  action_id_ = value;
  // @@protoc_insertion_point(field_set:msg.Header.action_id)
}

// -------------------------------------------------------------------

// Body

// -------------------------------------------------------------------

// Msg

// required .msg.Header header = 1;
inline bool Msg::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg::clear_header() {
  if (header_ != NULL) header_->::msg::Header::Clear();
  clear_has_header();
}
inline const ::msg::Header& Msg::header() const {
  // @@protoc_insertion_point(field_get:msg.Msg.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::msg::Header* Msg::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::msg::Header;
  }
  // @@protoc_insertion_point(field_mutable:msg.Msg.header)
  return header_;
}
inline ::msg::Header* Msg::release_header() {
  clear_has_header();
  ::msg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Msg::set_allocated_header(::msg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:msg.Msg.header)
}

// optional .msg.Body body = 2;
inline bool Msg::has_body() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg::set_has_body() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg::clear_has_body() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg::clear_body() {
  if (body_ != NULL) body_->::msg::Body::Clear();
  clear_has_body();
}
inline const ::msg::Body& Msg::body() const {
  // @@protoc_insertion_point(field_get:msg.Msg.body)
  return body_ != NULL ? *body_ : *default_instance_->body_;
}
inline ::msg::Body* Msg::mutable_body() {
  set_has_body();
  if (body_ == NULL) {
    body_ = new ::msg::Body;
  }
  // @@protoc_insertion_point(field_mutable:msg.Msg.body)
  return body_;
}
inline ::msg::Body* Msg::release_body() {
  clear_has_body();
  ::msg::Body* temp = body_;
  body_ = NULL;
  return temp;
}
inline void Msg::set_allocated_body(::msg::Body* body) {
  delete body_;
  body_ = body;
  if (body) {
    set_has_body();
  } else {
    clear_has_body();
  }
  // @@protoc_insertion_point(field_set_allocated:msg.Msg.body)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
