// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class Test;

// ===================================================================

class Test : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Test) */ {
 public:
  Test();
  virtual ~Test();

  Test(const Test& from);

  inline Test& operator=(const Test& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Test& default_instance();

  void Swap(Test* other);

  // implements Message ----------------------------------------------

  inline Test* New() const { return New(NULL); }

  Test* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Test& from);
  void MergeFrom(const Test& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Test* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::uint32 a() const;
  void set_a(::google::protobuf::uint32 value);

  // repeated uint32 yux = 2;
  int yux_size() const;
  void clear_yux();
  static const int kYuxFieldNumber = 2;
  ::google::protobuf::uint32 yux(int index) const;
  void set_yux(int index, ::google::protobuf::uint32 value);
  void add_yux(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      yux() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_yux();

  // @@protoc_insertion_point(class_scope:Test)
 private:
  inline void set_has_a();
  inline void clear_has_a();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > yux_;
  ::google::protobuf::uint32 a_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static Test* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Test

// optional uint32 a = 1;
inline bool Test::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Test::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Test::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Test::clear_a() {
  a_ = 0u;
  clear_has_a();
}
inline ::google::protobuf::uint32 Test::a() const {
  // @@protoc_insertion_point(field_get:Test.a)
  return a_;
}
inline void Test::set_a(::google::protobuf::uint32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:Test.a)
}

// repeated uint32 yux = 2;
inline int Test::yux_size() const {
  return yux_.size();
}
inline void Test::clear_yux() {
  yux_.Clear();
}
inline ::google::protobuf::uint32 Test::yux(int index) const {
  // @@protoc_insertion_point(field_get:Test.yux)
  return yux_.Get(index);
}
inline void Test::set_yux(int index, ::google::protobuf::uint32 value) {
  yux_.Set(index, value);
  // @@protoc_insertion_point(field_set:Test.yux)
}
inline void Test::add_yux(::google::protobuf::uint32 value) {
  yux_.Add(value);
  // @@protoc_insertion_point(field_add:Test.yux)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Test::yux() const {
  // @@protoc_insertion_point(field_list:Test.yux)
  return yux_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Test::mutable_yux() {
  // @@protoc_insertion_point(field_mutable_list:Test.yux)
  return &yux_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
